server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  datasource:
    url:      ${SQL_CONNECTION}
    username: ${SQL_USER}
    password: ${SQL_PASSWORD}

  flyway:
    locations: classpath:sql/migration
